server:
  port: 8080
spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:8888
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/